optionsviz:  # Ajoutez ce niveau pour correspondre au nom du subchart
  technicalSecret:
    type: SealedSecret
    githubSecret: "AgBjy3IDDsxdJsDebyJUPzY3gqD6rDAdz2D/1lDD/FsRRCCDKCgLjY3KZT0HwI0N+LrsL3dCS9RJ2xBLl6rABqQ1aydoHxwZSvorZeEjkkLEHJqIdpzrDiNKNlI786gVeReQRJ7KbAxrFCT9SQoCw39L5ZsLLuDVSBriUaWpm4SDgG5YfPXV+8UkxdfuPtoNBQWnE1TJjzBrNQ62teQxBya5ufVebC4dGbIT2cMZqoV6nESfszi5yeJUFSHTSuzHJMl/RLaNu5sIUw4YpV10WNuPrAiQl2wZFfqnBjYNzNdSVElBMNb5xuwpL2xXdHgmnxTgDBsVbFzJaaFj7BmsdeCG1Rh8PqIQTfqDvRoJEhN+B1b4uUj2YcYH6doelgN4wkjrS82U2+KI0BpYaN3RN6NXosY2knYapf6BlC2QLF4E65noVe8E9hGbmizDfZSChVexr6HA+C179DaqUSGfrqYquOwIkVrO6RNQfrqik4u/Qi7nCTfmEA1r4U9qxIRkmxiyU46Ga0Xv/vhKafv3FA7bW691FPhCIODXm94j3JFYn1PaBQZ085nh5dy59dWOI0Si3RDYL+5D4Jch2XqvBE2t9iU3IeOOdmzuGZxwLxR3No40L0n4OhIYYgRUZrzviyqzj78rAd7NyxaQA3X777WAj92uLfpw8VgzZsplPTriJmDs88WwPEl3J1IqTsQcbnEnuAsuloMSgAe+iX6tYPzfhGJyKMsN1ZG8vuvXhWbegLCpUCAbm00oi6/qSf62e5DaqujNuhqaPf5zUYkMuBbHUzu9MjzXDI5OdMm/ev1gEF6KZQhioVDhc3mdL06jKbB8m+d5t4TgyZJpmeMkMn3rQLoAQwMEDChYueCnPjbw56jdblSxYfnBfSF1KOWjg9gwbJnEPpgxzhxpYnIJ3fUE4LGuwUCwNuY87ptPW3WnH6e8bjZC0MLJJAxwbxlcxGaFIF92Olxo0Yp1oxacIgapPCIq+Zrudo3ILKR4Ig5GgcrCWjsxPvan0pehkoDj6Yqd"


  module: optionviz
  name: optionviz
  environment: dev
  replicas: 1
  containers:
    image: ghcr.io/hugogobbi/optionsviz
    name: optionsviz
    tags: latest
    imagePullSecrets:
      name: technical-secret
    ports:
      containerPort: 80 # Changed from 'http' to '80' for consistency
    resources:
      requests:
        memory: "1Gi"        # Augmenté de 512Mi à 1Gi
        cpu: "500m"          # Augmenté de 200m à 500m
      limits:
        memory: "2Gi"        # Augmenté de 1024Mi à 2Gi
        cpu: "1000m"         # Augmenté de 200m à 1000m (équivalent à 1 CPU)
    sqlite:
      enabled: false
    redis:
      enabled: false
  service:
    port: 80
    targetPort: 80
  ingress:
    host: mm.ch  
    enabled: true 
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx  # Added this common annotation
        nginx.ingress.kubernetes.io/rewrite-target: /$1  # If you want path rewriting
    spec:
      path: /optionviz
      pathType: Prefix
  configmap:
    enabled: false