technicalSecret:
  type: "sealedSecret"
  githubSecret: "AgCNhItqWZOrUQlbbjlVPu91v0tV0Dtssh6e3e6jNKmXj/xc6jRg+Ii5eAPya8R2SQXZFRG2WL1G4TuirMEjbkgeG7eBK8yPdwy+A6BUvT+e1Dz8tTgNVTzO8JlEsZzUP/tn6qwRrLoRGvGI6exufKdiukpseIuvoJXgcTxFsOjYtBIQzOBlHjK7ezo6Ac4o0mEthWIfcpRf2P3jA2hKNbvHXb+giFOB74x57m/SoKxPN/6tKvqwsqXL1ae00BmddEunXpYdrMsr2ghO0WQtAevh2wlKmAhrQYrXDQjVrpNx5LhqIDzJG4RR2YJukWWO/ULLgO9xSA0CwssNH4sr7cdXSkMpFJLCSfoltzF9C3wlWK5lgg1O8467qCAP2FUbUES5LUb8ie28YrT98d64ieTLQvhtE9uFiBdAPtD0HlcTC/CqB9yjPn6bCZ9VK8+WSoXOoKdsL7CdzEPjwwbhZnplNvEdQTlPXX9tlvybEiohoLQ+cvLGfg+qYOuYqqdkv3yWUGTFD8cADeINTRt2Xt2OwF0oFCzk2PmSH6y1UEXek+upR1RiVfMLsa07j/Wa58+mP3QsZlYt1e9OMCkU4BA+Bolhl8Tgda1FexY7NPL2P2SAxmShpPjlg/9Unho1I+SGTfsbNrCjWjmGULwfX9QapKzwHhIWM+zso4WotNGKhaNe3c9ODq3vMtsB9fbuyAagfL4/bFXAUMWSNhaTwZHfVpNZc9cf/0s+crpuUwOGgkYAF6bDar8zBQCJe68SlJZpaaCYTAfH0VygXHFmknQ4Ab9GQ+JeFW6REsXqtyt4ra0EhWCGyaJyxpeu9P+Jyph6IRvMsyvGbdde8q4057X/H5vt95rC3BhyH1AX7nkN7RZjnuPDd5EJ6dU1SIj9ukg7+2h5jyotcxZMjVPas0SZzg4twW1SYNTKvcvc6D9b3rBn8Ex3JH+HCDrnx/qQlW3E1Boer/uUmycmL/gkMzZLwK5cFnVS5cYYCAEqGCrnWYiviWe9"  # Collez ici la valeur encryptée

optionsviz:  # Ajoutez ce niveau pour correspondre au nom du subchart
  module: optionviz
  name: optionviz
  environment: dev
  replicas: 1
  containers:
    image: ghcr.io/hugogobbi/optionsviz
    name: optionsviz
    tags: latest
    ports:
      containerPort: 80 # Changed from 'http' to '80' for consistency
    resources:
      requests:
        memory: "1Gi"        # Augmenté de 512Mi à 1Gi
        cpu: "500m"          # Augmenté de 200m à 500m
      limits:
        memory: "2Gi"        # Augmenté de 1024Mi à 2Gi
        cpu: "1000m"         # Augmenté de 200m à 1000m (équivalent à 1 CPU)
    sqlite:
      enabled: false
    redis:
      enabled: false
  service:
    port: 80
    targetPort: 80
  ingress:
    host: mm.ch  
    enabled: true 
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx  # Added this common annotation
        nginx.ingress.kubernetes.io/rewrite-target: /$1  # If you want path rewriting
    spec:
      path: /optionviz
      pathType: Prefix
  configmap:
    enabled: false