optionsviz:

  module: optionsviz
  name: optionsviz
  environment: dev
  replicas: 1
  containers:
    image: ghcr.io/hugogobbi/optionsviz
    name: optionsviz
    tags: latest
    ports:
      containerPort: 80
    resources:
      requests:
        memory: "256Mi"    # Réduit de 1Gi
        cpu: "200m"        # Réduit de 1000m
      limits:
        memory: "512Mi"    # Réduit de 2Gi
        cpu: "400m"        # Réduit de 1000m
  sqlite:
    enabled: false
  redis:
    enabled: false
  service:
    type: NodePort # ClusterID
    port: 80
    targetPort: 80
  configmap:
    enabled: false