optionsviz:
  module: optionviz
  name: optionviz
  environment: dev
  replicas: 1
  containers:
    image: ghcr.io/hugogobbi/optionsviz
    name: optionsviz
    tags: latest
    imagePullSecrets:
      name: technical-secret
    ports:
      containerPort: 80
    resources:
      requests:
        memory: "256Mi"    # Réduit de 1Gi
        cpu: "200m"        # Réduit de 1000m
      limits:
        memory: "512Mi"    # Réduit de 2Gi
        cpu: "400m"        # Réduit de 1000m
  sqlite:
    enabled: false
  redis:
    enabled: false
  service:
    port: 80
    targetPort: 80
  ingress:
    host: mm.ch
    enabled: true
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      path: /optionviz
      pathType: Prefix
  configmap:
    enabled: false