name: CI

on:
  push:
    branches: 
      - prod

env:
  BRANCH_PAGES: github-pages
  BRANCH: prod
  REPO_DEP: https://raw.githubusercontent.com/MiletoCarmelo/DEVOPS_HELM_generic_react_frontend/github-pages
  DIR: umbrella-optionsviz
  REPO_NAME: generic-react-frontend
  VALUES_FILE: values.dev.yaml

permissions:
  contents: write
  packages: write  # Allows pushing images to the GitHub Container Registry

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_PAGES }}

      - name: rm -rf all 
        run: rm -rf *

      - name: Fetch prod branch
        run: |
          git fetch origin prod:prod
    
      - name: Merge prod
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git merge prod --no-edit

      - name: cd in the folder
        run: cd {{ env.DIR }}

      - name: helm add repo
        run: helm repo add {{ env.REPO_NAME }} {{ env.REPO_DEP }}
      
      - name: helm update repo
        run: helm dependency build  
      
      - name: helm template 
        run: helm template optionsviz . -f {{ $VALUES_FILE }} -n dev > generated-manifests.yaml     

      - name: push to github-pages
        run: git push origin ${{ env.BRANCH_PAGES }}
      

