name: CI
on:
  push:
    branches:
      - prod

env:
  BRANCH_PAGES: github-pages
  BRANCH: prod
  REPO_DEP: https://raw.githubusercontent.com/MiletoCarmelo/DEVOPS_HELM_generic_react_frontend/github-pages
  DIR: umbrella-optionsviz
  REPO_NAME: generic-react-frontend
  VALUES_FILE: values.dev.yaml

permissions:
  contents: write
  packages: write

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .  # Point vers le répertoire racine
          charts_url: https://raw.githubusercontent.com/${{ github.repository }}/${{ env.BRANCH_PAGES }}
          branch: ${{ env.BRANCH_PAGES }}
          target_dir: ${{ env.CHART_DIR }}
          linting: false

  generate-manifests:
    needs: [release-chart]  # Spécifie que ce job doit attendre que release-chart soit terminé
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_PAGES }}

      - name: unzip tgz file
        run: tar -xvf ${{ env.CHART_DIR }}/${{ env.REPO_NAME }}-*.tgz -C ${{ env.DIR }}
        
      - name: cd in the folder
        run: cd ${{ env.DIR }}

      - name: helm add repo
        run: helm repo add ${{ env.REPO_NAME }} ${{ env.REPO_DEP }}

      - name: helm update repo
        run: helm dependency build

      - name: helm template
        run: helm template optionsviz . -f ${{ env.VALUES_FILE }} -n dev > generated-manifests.yaml

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add generated-manifests.yaml
          git commit -m "Update generated manifests"
          git push origin ${{ env.BRANCH_PAGES }}