name: CI

on:
  push:
    branches: 
      - prod

env:
  BRANCH_PAGES: github-pages
  BRANCH: prod
  CHART_DIR: umbrella-optionsviz

permissions:
  contents: write
  packages: write  # Allows pushing images to the GitHub Container Registry

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .  # Point vers le répertoire racine
          charts_url: https://raw.githubusercontent.com/${{ github.repository }}/${{ env.BRANCH_PAGES }}
          branch: ${{ env.BRANCH_PAGES }}
          target_dir: ${{ env.CHART_DIR }}
          linting: false

          
      - name: summary 
        run: echo "https://raw.githubusercontent.com/${{ github.repository }}/${{ env.BRANCH_PAGES }}"
      

